### ISSUE TITLE
which gensim version should be

### ISSUE THREAD

**Issue by SeekPoint** [mickeystroller/SynSetMine-pytorch#1]

**Comment by mickeysjm** [comment]
The gensim version I used is 3.4.0. Actually, the only place I use gensim is in *utils.py* for loading word2vec formatted embeddings. Maybe other gensim versions should also be OK.

**Comment by SeekPoint** [comment]
the old one doesn;t support from gensim.models.poincare import PoincareKeyedVectors

**Comment by mickeysjm** [comment]
I also guess the PoincareKeyedVectors does not support the older version. But as I don't actually use Poincare Embedding in this work, I remove the dependency and the latest commit should work fine. Thanks for pointing this out.
